agent:
  tau: 0.05
#  tau: 0.01

actor:
#  learning_rate: 0.001
#  gradient_limit: 0.0
#  gradient_limit: 0.01
#  layers: [50, 50, 50]
#  activation: 'elu'
#  tanh_preactivation_loss_coefficient: 1.0
#  tanh_preactivation_loss_coefficient: 0.0

critic:
  learning_rate: 0.005
#  learning_rate: 0.01
  gradient_limit: 1.0
#  gradient_limit: 0.0
  layers_before_action: [50, 50]
  layers_after_action: [50, 50, 50]
  activation: 'elu'
#  l2_regularization_coefficient: 0.0
  l2_regularization_coefficient: 0.0001
  last_layer_tanh: True
#  last_layer_tanh: False
