general:
  name:
#  gym_continuous_env: 'Pendulum-v0'
#  gym_continuous_env: 'MountainCarContinuous-v0'
  gym_continuous_env: 'LunarLander-v2'
  random_seed: 123
#  random_seed: 456
#  random_seed: 789
  updates_cycle_count: 10000
  episodes_per_update: 16
#  model_updates_per_cycle: 40
  model_updates_per_cycle: 400
  max_path_slack: 1.5
  gpu_usage: 0.9
  actor_gpu_usage: 0.9
#  actor_processes: 2
  actor_processes: 6
  write_train_summaries: 500
  save_model_every_cycles: 100
  max_steps: 300

model:
  buffer_size: 1000000
#  batch_size: 128
  batch_size: 512
  gamma: 0.99
  random_action_probability: 0.2
  #random_noise_std: 0.05

test:
  test_every_cycles: 50
  number_of_episodes_per_actor: 50
#  show_best: True
  show_best: False

evolution:
  population: 1
  softmax_temperature: 1.0
  use_default_configration: True  # to benchmark vs regular agent
#  use_default_configration: False